### ISSUE TITLE
Duplizieren: createdate/createuser und updatedate/updateuser aktualisieren

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/yform_usability#102]
Wir haben hier ein Szenario, wo wöchentlich ein Newsletter mit neuen Einträgen rausgeht, die aus einer YForm Table stammen. Wir nutzen dort, wie sonst auch üblich, `createuser`, `createdate` und die update-Pendants als Felder. Der Newsletter richtet sich nach dem `createdate`, womit der duplizierte Eintrag, wenn seine Vorlage älter als 1 Woche ist, nie in einem Newsletter erscheint.

Deshalb und auch wegen genereller Logik würde ich diese Quasi-Standard-Felder gern aktualisiert sehen. Gern auch einstellbar. Ich hab es bei mir im projekt jetzt wie folgt geändert:

```php
                 if ($field == 'status') {
                     $iSql->setValue($field, 0);
                 }
                 elseif ($field == 'createdate' || $field == 'updatedate') {
                     $iSql->setValue($field, date("Y-m-d H:i:s"));
                 }
                 elseif ($field == 'createuser' || $field == 'updateuser') {
                     $iSql->setValue($field, \rex::getUser()->getLogin());
                 }
                 elseif ($field != 'id') {
                     $iSql->setValue($field, $sql->getValue($field));
                 }
```

**Comment by alxndr-w** [comment]
duplicate #88 - das Problem ist, dass bisher der Datenbank-Eintrag per rex_sql geändert wurde und damit alles andere umgeht. #100 finalisieren würde das Problem lösen.
