### ISSUE TITLE
yform 4.0.2 suche aktiv - drag and drop reihenfolge nicht sichtbar

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/yform_usability#107]
Hat man bei der Tabelle die Suche aktiviert ist die drag and drop reihenfolge via prio in der Tabllenübersicht nicht zu sehen.
Deaktiviert man die Suiche ist die drag and drop reihenfolge zu sehen.

**Comment by alxndr-w** [comment]
Ich verstehe nicht, was damit gemeint ist. Ein Screenshot würde helfen.
