### ISSUE TITLE
Fehler im aktuellen Release 1.2.1 [Sammelissue]

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#11]
Nach der Erstinstallation des aktuellen Release hat yform_usability keine Wirkung. Außerdem wird die Einstellungsseite hinter dem neuen Reiter "yform_usability" nicht angezeigt. Diese sollte ohnehin nur "Usability" heißen und nicht wie der Addon-Key.

**Comment by lexplatt** [comment]
Stimmt... es werden keine Default-Werte bei der Installation gesetzt. Muss ich mir nochmals anschauen.

**Comment by alexplusde** [comment]
Vlt. nochmal das Update aus dem Installer rausnehmen?

**Comment by lexplatt** [comment]
neuer installer online. Danke für die Hinweise

**Comment by alexplusde** [comment]
Das Release ist immer noch fehlerhaft. Wenn man eine bestehende Version updatet - es kommen z.T. Javascript-Alerts.

die 1.1-Version hingegen funktioniert in dieser Hinsicht tadellos.

**Comment by lexplatt** [comment]
kannst du mir sagen unter welchen Bedinungen die Alerts auftreten (beim Sortieren oder bei Status-Änderung, ...)?
Welche Alert-Msg erhälst du?

**Comment by alexplusde** [comment]
Ich erhalte die Meldung beim verschieben. Ich kann diese altert-Meldungen leider nicht rauskopieren, sie ist ellenlang und enthält Sonderzeichen - kann gerade keinen Screenshot liefern, weil das Projekt schon live ist. 

Generell wäre ein console.log() an der Stelle doch viel empfehlenswerter, als ein Alert.

**Comment by alexplusde** [comment]
@rotzek du hattest doch auch Meldungen beim Duplizieren und konntest sie rauskopieren, kannst du die hier mal posten?

**Comment by ynamite** [comment]
Hab gerade das neue Release gezogen. Die Standardeinstellungen werden nicht gesetzt und die Einstellungsseiten für Usability speichert keine Werte.

Hab in yform.manager.usability.php auf Zeile 39 folgendes eingefügt:
```
\rex_addon::get('yform_usability')->setConfig('status_tables', Array ( 0 => 'all' ));
\rex_addon::get('yform_usability')->setConfig('sorting_tables', Array ( 0 => 'all' ));
\rex_addon::get('yform_usability')->setConfig('duplicate_tables', Array ( 0 => 'all' ));
```
Danach klappt's mit dem speichern.

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/yform_usability/pull/12

**Comment by alexplusde** [comment]
@IngoWinter @ynamite @lexplatt 

Auch nach Ingos PR folgende Fehler:

1. Übersetzung fehlt

![bildschirmfoto 2017-04-18 um 14 35 07](https://cloud.githubusercontent.com/assets/3855487/25131018/900d050c-2444-11e7-9ed3-222122648ff1.png)


2. Prio-Drag-Drop funktioniert nicht (Wert wird nicht übernommen)

3. Prio Drag-Drop manchmal beim hovern versetzt
![bildschirmfoto 2017-04-18 um 14 34 43](https://cloud.githubusercontent.com/assets/3855487/25131009/8b98b818-2444-11e7-93e1-f00d153648af.png)


4. Duplizieren / online benötigt `&nbsp;`, damit nicht umbrochen wird.

![bildschirmfoto 2017-04-18 um 14 34 41](https://cloud.githubusercontent.com/assets/3855487/25131004/887838e8-2444-11e7-8517-ae61b7d5020d.png)

**Comment by IngoWinter** [comment]
@alexplusde kannst du Punkt 2 debuggen? Es muss ja irgendwo in der _updatesort() in /lib/Api.php schiefgehen...

**Comment by lexplatt** [comment]
ich habs gerade bei mir getestet und läuft einwandfrei. Schau mal im Console.log nach welche/ob du einen Fehler erhälst

**Comment by alexplusde** [comment]
in der console.log passiert nichts.

Wenn ich einen Eintrag bspw. um eins nach oben verschiebe, wird er ganz an Position eins gesetzt. Prio-Feld ist nicht beschränkt. (damit hat aber yform_usability scheinbar ein grundsätzliches Problem.

Gut wäre auch, wenn die Tabellenansicht komplett neu lädt, im Moment wird ja die Änderung der Reihenfolge der Datensätze nur simuliert.

**Comment by lexplatt** [comment]
ich kann mir vorstellen dass dies damit zusammenhängt, dass die Tabelle nicht nach prio sortiert ist. habe nun einen Check eingebaut dass dies nicht mehr vorkommen kann.
Dass eine Übersetzung fehlt und CSS Probleme auftauchen kann ich nicht nachvollziehen.

**Comment by alexplusde** [comment]
Das haben wir in verschiedenen parallelen Installationen so.

Ich nehm noch mal den aktuellen Stand und versuche es erneut.

**Comment by alexplusde** [comment]
Das CSS-Problem passiert, wenn die Anzahl der angezeigten Tabellenfelder breiter wird, als Platz ist - dann passiert automatisch ein Umbruch. Das kann man aber beheben, indem man zwischen Icon und Beschriftung ein geschütztes Leerzeichen verwendet oder dem Feld `white-space: nowrap` zuweist.

https://www.impressivewebs.com/css-white-space/

**Comment by lexplatt** [comment]
ich hatte mich eigentlich auf das Hover-Problem bezogen :)

**Comment by alexplusde** [comment]
Also wenn das Problem bei euch nicht Auftritt, habe ich ja dafür Verständnis - aber sowas hier muss man doch merken: 

https://www.dropbox.com/s/qjec4f5nt2hg8ot/demo%20yform%20problem.mp4?dl=0

![bildschirmfoto 2017-04-19 um 11 33 59](https://cloud.githubusercontent.com/assets/3855487/25173401/3c1d9046-24f4-11e7-923e-99652ff2aafe.png)
![bildschirmfoto 2017-04-19 um 11 34 05](https://cloud.githubusercontent.com/assets/3855487/25173402/3c1e2c9a-24f4-11e7-9a21-a64e7e116a2b.png)
![bildschirmfoto 2017-04-19 um 11 34 30](https://cloud.githubusercontent.com/assets/3855487/25173403/3c211112-24f4-11e7-9644-e3151896ecf5.png)

**Comment by IngoWinter** [comment]
@alexplusde kannst du den Film bitte nochmal hochladen, mit ner besseren Auflösung und nem gescheiten Soundtrack? Das stumme Gepixel kann sich doch keiner antun...

**Comment by lexplatt** [comment]
@alexplusde besteht der Fehler immer noch?

**Comment by alexplusde** [comment]
Ja.

**Comment by lexplatt** [comment]
gibt es die Möglichkeit das auf einer eurer Install zu überprüfen bzw. kann ich da irgendwie mal reinschauen?

**Comment by IngoWinter** [comment]
Ich muss zugeben, dass ich gerade nicht mehr weiss, um welches Problem es genau geht :)
Bei mir tats soweit alles und aus dem Film werde ich nicht so recht schlau...

**Comment by alexwenz** [comment]
Ich habe es gerade frisch installiert über den Installer (Version 1.2.1): wenn ich in yform-TableManager auf den Link "yfrom-usability" klicke, kommt eine Seite mit "Tabelle nicht gefunden". Ist das bekannt?

Zum Film: Alex+ wollte damit zeigen, dass beim Sortieren bei ihm scheinbar die gewünschte Sortierung nicht übernommen wird: d.h. er sortiert einen Datensatz an Position 7, lädt neu und dieser Datensatz ist nach dem Reload der Seite an Position 1.

**Comment by alexplusde** [comment]
@lexplatt ja, ich schick dir die Zugangsdaten, wenn ich wieder im Büro bin, denn ich bin überall runter auf die Version 1.1

Bis dahin: Was @alexwenz sagt. Sortierung für den Popo.

**Comment by alexplusde** [comment]
gefixt in aktueller GitHub-Version, Release kommt...

**Comment by lexplatt** [comment]
Release ist online ;)
