### ISSUE TITLE
YFORM_DATA_STATUS_CHANGED wird nicht getriggert

### ISSUE THREAD

**Issue by netzproductions** [FriendsOfREDAXO/yform_usability#110]
**Description / Beschreibung**
Der EP YFORM_DATA_STATUS_CHANGED wird nicht getriggert, wenn man in der Datenübersicht in yForm den Status eines Datensatzes ändert.

**Affected versions / Verwendete Versionen**
REDAXO: 5.14.1
PHP: 7/8

**Comment by alxndr-w** [comment]
Siehe #88
