### ISSUE TITLE
Warning: filemtime(): stat failed for `...\assets\addons\yform_usability\styles.css`

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_usability#114]
**Description / Beschreibung**
Warning: filemtime(): stat failed for `...\assets\addons\yform_usability\styles.css` in redaxo\src\addons\yform_usability\boot.php on line 51

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/yform_usability/pull/123

**Comment by eaCe** [comment]
Das sollte sich erledigt haben, die Styles liegen nun im Repo

**Comment by olien** [comment]
Ist in Version 2.0.7 noch da

**Comment by olien** [comment]
Alles aktualisiert. Cache gelöscht und deinstalliert...

![image](https://user-images.githubusercontent.com/330516/212676359-1fdd6139-3be6-4dc5-ae19-c1cba2ad7de7.png)

**Comment by eaCe** [comment]
@olien bitte die GH-Version testen. Ist noch nicht released
