### ISSUE TITLE
Komisches HTML in choice-Status-Feld

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_usability#115]
**Description / Beschreibung**
![image](https://user-images.githubusercontent.com/3855487/202215501-1f434e8a-839a-417c-be7b-287f5f7f23e6.png)

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by eaCe** [comment]
Ist das nicht eher ein YForm Issue?

**Comment by alxndr-w** [comment]
@eaCe ich glaube nicht, denn die Status-Schalt-Funktion kommt ja aus yform_usability.

**Comment by eaCe** [comment]
@alxndr-w sicher das du nicht versehentlich nbsp's eingefügt hast? Bei mir wird Text korrekt ausgegeben, auch mit leerzeichen

**Comment by alxndr-w** [comment]
Scheinbar betrifft es niemanden und ich habe jetzt mein eigenes Value zum Umschalten des Status:
https://github.com/alexplusde/yform_field/releases/tag/2.3.0
