### ISSUE TITLE
2.0.6-beta > Keine style.css Kompilierung?

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/yform_usability#116]
**Description / Beschreibung**

Bei mir wird die assets\addons\yform_usability\style.css nicht generiert.
Bei einem Update, ist es noch die alte. Bei einer frischen Neuinstallation fehlt sie.

Ändere ich in der boot.php die Zeile
`if ($addon->getProperty('compile')) {`
wieder in 
`if (1 == rex_get('compile', 'int') || !file_exists($this->getAssetsPath('styles.css'))) {`
klappt es.

Kann das jemand bestätigen?

**Affected versions / Verwendete Versionen**

<details>
<summary>System report (REDAXO 5.14.1, PHP 7.4.33, MariaDB 10.3.36)</summary>

| Packages                 |            |
| -----------------------: | :--------- |
|                    yform | 4.0.4      |
|               yform/docs | 3.3.1      |
|              yform/email | 4.0.4      |
|            yform/manager | 4.0.4      |
|              yform/tools | 4.0.4      |
|    yform_spam_protection | 1.2.1      |
|          yform_usability | 2.0.6-beta |

</details>

**Comment by alxndr-w** [comment]
Bei mir war das jetzt beim Update auch so. Leider habe ich dieses System von Addon-angestoßenem Compiling nie verstanden (warum nicht die generierte CSS-Datei mitliefern?).

**Comment by alxndr-w** [comment]
#114

**Comment by eaCe** [comment]
https://github.com/FriendsOfREDAXO/yform_usability/pull/123
