### ISSUE TITLE
duplizierten Datensatz auszeichnen

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/yform_usability#117]
Aktuell erkennt man einen gerade duplizierten Datensatz nicht wirklich, nur an der ID und am Status (falls vorhanden).
Kann man den irgendwie markieren? 

Eine Variante wäre, das die betroffene Zeile kurz gehighlighted werden würde, so ähnlich wie beim Installer wenn ein Addon installiert wurde und dieses farblich hervorgehoben wird.

**Comment by alxndr-w** [comment]
Das bessere Verhalten, das @tbaddade in dem Zusammenhang vorgeschlagen hatte (wenn ich mich recht erinnere), wäre, dass duplizieren gar nicht erst den Datensatz erzeugt, sondern in die Eingabemaske springt. 

Das würde auch das Problem lösen, wie man mit Relationen umgeht.

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_yform/pull/1344 

close / Anregung in YForm direkt?

**Comment by eaCe** [comment]
Sehe es wie Alex, würde hier schließen @ynamite
