### ISSUE TITLE
Satz duplizieren: (Unique-)Validatoren bleiben unbeachtet

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/yform_usability#125]
**Description / Beschreibung**

Man kann problemlos Datensätze duplizieren, die anschließend zu doppelten Einträgen in Unique-Feldern führen.

Test-Szenario: 

- in einer Tabelle erhält ein Feld einen Validator auf "Unique".
- Erfasen eines neuen Datensatzes, der einen bereits vorhandenen  Wert erhält. Wie erwartet kommt beim Speichern eine Fehlermeldung. 
  <img width="688" alt="grafik" src="https://user-images.githubusercontent.com/10065904/210847791-12860a78-b51d-4792-91a8-cda1ef98398a.png">

- Den vorhandenen Satz per Duplizieren-Aktion kopieren: klappt problemlos.
   <img width="755" alt="grafik" src="https://user-images.githubusercontent.com/10065904/210847979-82dbde4c-1698-4ab7-806b-5948893b3f93.png">

Das darf m.E. so nicht sein.

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.2
PHP: 8.2.0
Database: Mysql 8.0.17
Browser: 
AddOns: YForm_usability 2.0.7

**Comment by alxndr-w** [comment]
Könnte obsolet sein durch https://github.com/yakamara/redaxo_yform/pull/1344

**Comment by eaCe** [comment]
Ich würde das hier auch schließen, ich denke es ist gut wenn sich yform selbst darum kümmert.

**Comment by christophboecker** [comment]
IST erledigt seit yform selbst Klonen kann.
