### ISSUE TITLE
Notiz: Duplizieren deaktivieren

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_usability#126]
wenn: https://github.com/yakamara/redaxo_yform/pull/1344
released.

**Comment by alxndr-w** [comment]
Wenn wir auf Kompatibilität wert legen, folgt jetzt ein Release in dem geprüft wird, ob eine aktuelle YForm-Version aktiv ist und deaktivieren den entsprechenden Button von YForm Usability. Gemerged ist der PR ja bereits.

**Comment by alxndr-w** [comment]
Ich habe das mit dem Klonen aus YForm direkt jetzt schon ein paar Mal in unterschiedlichen Tablesets ausprobiert. Es ist super und bleibt am YForm-Ablauf inkl. EPs. Ich würde `question` hier entfernen.
