### ISSUE TITLE
Sortieren per Spaltenüberschrift

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/yform_usability#13]
Eine manuelle Sortierung von Datensätzen per D&D macht imho nur Sinn, wenn die Anzahl der Datensätze halbwegs überschaubar ist. Deswegen deaktiviere ich das Sortieren per Spaltenüberschrift eigentlich immer:

![unbenannt-1](https://cloud.githubusercontent.com/assets/7223820/24980386/3e8a25ea-1fd8-11e7-9f93-b88371b551f3.png)

Zudem macht das Sortieren per D&D wenig Sinn, wenn nicht nach Prio sortiert ist. Wie handhabt ihr das/ sollte man das Deaktivieren der Sortierung per Spaltenüberschrift vielleicht als Option ins Addon übernehmen?

**Comment by alexplusde** [comment]
Ja, fände ich gut. Wir sind auch schon darübergestolpert, dass die Tabelle nicht initial nach Prio sortiert. Nur dann dürfte in meinen Augen das Griff-Icon angezeigt werden. 

In die Einstellung sollte sowieso auch der Hinweis, selbst, wenn es klar ist. Vielleicht direkt in den Tabellennamen bei der Auswahl:

![image](https://cloud.githubusercontent.com/assets/3855487/25133624/8063f3dc-244d-11e7-88f2-08a0b194a743.png)

**Comment by lexplatt** [comment]
Habe soeben einen Check eingebaut der überprüft ob nach prio sortiert wird oder nicht.
Wenn nicht kann man nicht mehr sortieren

**Comment by alexplusde** [comment]
Klasse, danke! (Wie erfährt der Nutzer davon, dass er die Tabelle falsch eingestellt hat?)

**Comment by lexplatt** [comment]
Leider nur indem er nicht mehr sortieren kann... weiters gibt es auch das Problem dass er in der List nicht wirklich nach "Prio" manuell sortiere kann.
Für Vorschläge dies benutzerfreundlicher zu machen bin ich gerne offen

**Comment by alexplusde** [comment]
Zumindest ein Label bei den Einstellungen des Usability-Tabs wäre hilfreich.

**Comment by IngoWinter** [comment]
@alexplusde magst du einen knackigen Text fürs Usability Tab schreiben? Ich baus dann auch gerne ein :)

**Comment by alexplusde** [comment]
**Im Table Manager in der jeweiligen Tabelle**

> "Die Tabelle `rex_table` besitzt kein Status-Feld. Der Status-Schalter des Addons yform_usability wurde deaktiviert` Jetzt hinzufügen oder Status-Schalter deaktivieren" 
[`Jetzt hinzufügen` linkt direkt auf den Table Manager > Tabelle > Feld bearbeiten > checkbox-Feld hinzufügen]
[Status deaktivieren linkt dann auf die Einstellungs-Seite von yform_usability

> "Die Tabelle `rex_table` besitzt kein Prio-Feld. Die Drag&Drop-Sortierung des Addons yform_usability wurde deaktiviert`. Jetzt hinzufügen oder Drag&Drop deaktivieren"
[`Jetzt hinzufügen` linkt direkt auf den Table Manager > Tabelle > Feld bearbeiten > prio-Feld hinzufügen]
[Drag&Drop deaktivieren linkt dann auf die Einstellungs-Seite von yform_usability

> "Die Tabelle `rex_table` ist nicht nach kein Prio-Feld. Die Drag&Drop-Sortierung des Addons yform_usability wurde deaktiviert. Jetzt aktivieren oder Drag&Drop deaktivieren`" 
[Jetzt aktivieren linkt direkt auf den Table Manager > Tabelle > Einstellungen]
[Drag&Drop deaktivieren linkt dann auf die Einstellungs-Seite von yform_usability

**Im Usability-Addon**

bei Sortierung
> Um die Datensätze per Drag & Drop sortieren zu können, benötigt die Tabelle ein Feld vom Typ `prio`. Außerdem bitte in den Eigenschaften der Tabelle die Sortierung von `id` auf das `prio` ändern.

> Um die Datensätze per Klick online / offline zu schalten, benötigt die Tabelle ein `checkbox`, `select` oder `radio` Feld mit dem Feldnamen `status`, beschränkt auf die Werte `0` und `1`.

**Comment by IngoWinter** [comment]
@alexplusde hey vielen dank :)
die idee, einen ausführlichen und mit links versehenen hinweis direkt bei den tabellen im table-manager ist super. leider aber auch mit ner menge arbeit verbunden.
ich habe mal die texte im usability tab selbst eingebaut:
![text](https://user-images.githubusercontent.com/7223820/29288481-376f88be-8139-11e7-8b81-5334237b9889.png)
so richtig begeistert hat mich das aber nicht. das ist noch knapper, als die hinweise in der readme. zudem steht das alles schon in der readme :)
was hältste denn von dieser variante (der link zeigt auf die readme/ ? bei den addons):
![link](https://user-images.githubusercontent.com/7223820/29288621-add004fc-8139-11e7-90ba-d480301a94c0.png)
die variante mit link auf die readme finde ich geschmeidiger. du hast da markdown, du kannst mit screenshots arbeiten etc. und du kannst das dingen so detailliert vollknallen wie du möchtest...

**Comment by alexplusde** [comment]
die Variante mit dem Link versteckt die eigentliche Information, detaillierter benötigt man es an der Stelle gar nicht (und im Übrigen könnte man auch in die 1. Variante einen Link einfügen, bei dem es noch weitere Hilfe gibt).

Deshalb gefällt mir die 1. Variante besser.

Dass die anderen Meldungen an der Tabelle selbst nicht ohne weiteres möglich sind, haben wir ja schon in Slack besprochen und ist nachvollziehbar.

**Comment by alexplusde** [comment]
Allerdings hast du meine Meldung bearbeitet. Man kann sehr wohl radio, checkbox oder select benutzen ;)

**Comment by IngoWinter** [comment]
wie benutzt man denn checkbox? wir brauchen 2 texte - online und offline (oder sichtbar/unsichtbar oder an/aus). checkbox hat nur einen text...

**Comment by alexplusde** [comment]
bisher ging's mit der checkbox problemlos, ich habe das nach dem Update mit den Texten noch nicht getestet. Wird da nicht als Fallback online/offline genommen?

**Comment by IngoWinter** [comment]
Zumindest der relevante Code sieht nicht so aus. Könnte man aber flink nachrüsten...

**Comment by IngoWinter** [comment]
Ich hab den Hilfetext eingesetzt und ein Release draus gemacht (sowohl hier als auch im installer 1.2.7). Aktuelle kann ichs über den Installer nicht laden, kommt ne Fehlermeldung mit Prüfsumme.
Die Hilfetexte kannst du in den langfiles ändern.
