### ISSUE TITLE
Warnung `Undefined array key`

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/yform_usability#138]
**Description / Beschreibung**

Bei der Suche erscheinen Warnungen, möglicherweise nur im Zusammenhang mit der Suche über Choice-Felder:

```
Warning: Undefined array key 0 in redaxo/src/addons/yform_usability/lib/Extensions.php on line 314
Warning: Undefined array key "group_by" in redaxo/src/addons/yform/lib/yform/value/Choice/rex_yform_choice_list.php on line 56
Warning: Undefined array key "group_by" in redaxo/src/addons/yform/lib/yform/value/Choice/rex_yform_choice_list.php on line 56
Warning: Undefined array key "group_by" in redaxo/src/addons/yform/lib/yform/value/Choice/rex_yform_choice_list.php on line 56
```

Durch eine einfache Abfrage ob der array key existiert, verschwinden die Warnungen wieder.

**Affected versions / Verwendete Versionen**

<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.4, MariaDB 10.3.38)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.4      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.38 |
| Character set | utf8            |

| Database 2    |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.38 |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/111.0 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

| Packages                          |            |
| --------------------------------: | :--------- |
|                           adminer | 1.9.3      |
|                   article_presets | 1.2.0      |
|                            backup | 2.9.0      |
|                       be_password | 2.0.1      |
|                          be_style | 3.2.0      |
|               be_style/customizer | 3.2.0      |
|                   be_style/redaxo | 3.2.0      |
|                          be_tools | 1.7.8      |
|                           bloecks | 3.1.1      |
|                  bloecks/cutncopy | 3.1.1      |
|                 bloecks/dragndrop | 3.1.1      |
|                    bloecks/status | 3.1.1      |
|                    bs5_iconpicker | 1.0.5      |
|                     clear_content | 1.1.1      |
|                   consent_manager | 4.0.3      |
|                           cropper | 1.4.0      |
|                         developer | 3.9.2      |
|                        focuspoint | 4.0.4      |
|                        hyphenator | 1.3.0      |
|                           install | 2.11.1     |
|                            massif | 1.0.0      |
|                     massif_minify | 1.3.3      |
|                   massif_settings | 1.0.0      |
|                            mblock | 3.4.12     |
|                     media_manager | 2.14.0     |
|          media_manager_responsive | 1.1.4      |
|                  media_negotiator | 2.0.0      |
|                         mediapool | 2.13.0     |
|                          metainfo | 2.10.0     |
|                             mform | 7.2.8      |
|                         phpmailer | 2.12.0     |
|                              plyr | 3.21.0     |
|                           project | dev        |
|                          speed_up | 1.3.1      |
|                             sprog | 1.5.1      |
|                        statistics | 2.6.0      |
|                  statistics/media | 2.6.0      |
|                         structure | 2.15.0     |
|                 structure/content | 2.15.0     |
|                 structure/history | 2.15.0     |
|                  structure_tweaks | 1.4.0      |
|                             theme | 1.3.3      |
|                        theme_lock | 1.0.0      |
|                          tinymce5 | 1.2.17     |
|                          ui_tools | 1.2.2      |
| ui_tools/bootstrap-datetimepicker | 4.17.47    |
|        ui_tools/jquery-minicolors | 2.4.0      |
|                ui_tools/selectize | 0.2.0      |
|                          uploader | 2.4.1      |
|                               url | 2.1.0      |
|                         useragent | 2.3.0      |
|                             users | 2.10.0     |
|                             yform | 4.1.0      |
|                       yform/email | 4.1.0      |
|                     yform/manager | 4.1.0      |
|                       yform/tools | 4.1.0      |
|                     yform_adminer | 1.2.0      |
|                     yform_geo_osm | 1.2.8      |
|                  yform_quick_edit | 1.0.1      |
|             yform_spam_protection | 2.0-beta4  |
|                   yform_usability | 2.0.9      |
|                          yrewrite | 2.10.0     |

</details>

**Comment by eaCe** [comment]
Es ist bei mir immer leer, wenn das Feld ID auftaucht.
