### ISSUE TITLE
Status online / offline: Wechsel bei vorhandem DATETIME Feld

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/yform_usability#14]
Wenn man den Statuswechsel nutzt und in der verwendeten Tabelle neben dem Feld status noch ein oder mehere DATETIME Felder sind, werden diese beim Statuswechsel in der Übersicht einfach geändert und mit wirren Daten Daten überschrieben.

Aufgetreten in 1.1, da 1.2 ja nicht zu installieren geht.

**Comment by lexplatt** [comment]
wir sind gerade dabei die 1.2.2 zu releasen. Ich sag dir Bescheid sobald sie online ist

**Comment by lexplatt** [comment]
sollte nun mit der letzten Version behoben. Bitte einmal überprüfen

**Comment by rkemmere** [comment]
super. ist gerade getestet worden und funktioniert! Danke
