### ISSUE TITLE
Rechte zur Nutzung der Funktionen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_usability#143]
Die tollen Funktionen des AddOns sind immer aktiv ungeachtet der Nutzerrechte. 
Bei manchen Nutzern wäre es gut bestimmte Funktionen jedoch nicht zu erlauben. Dazu zählen vor allem der Status-Button und Drag&Drop. Ein allgemeines Recht würde schon reichen.  Die Einführung eines Rechtes wäre aber BC. Da nach dem Update alle User/Rollen entsprechend gesetzt werden müssten.

**Comment by alxndr-w** [comment]
Nutze doch stattdessen https://github.com/alexplusde/yform_field/blob/main/lib/yform/value/choice_status.php - das verhält sich wie ein ganz normales eigenes YForm-Feld und du kannst per YForm-EP die Ausgabe in der Datenübersicht nach deinen Wünschen unterbinden.
