### ISSUE TITLE
Frontenprobleme 

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/yform_usability#147]
Hi, ich habe die Tabelle rex_uder (ycom) erweitert und dort auch die lang_tabs benutzt.

wenn ich jetzt diese Formular nutze:

```
validate|ycom_auth|login|password|stayfield|{{ warning_message_enterloginpsw }}|{{warning_message_login_failed }}
objparams|form_name|login
objparams|form_anchor|login
objparams|form_ytemplate|tailwind3,bootstrap
objparams|submit_btn_label|{ Einloggen }}
text|login|{{ Benutzername }}|
password|password|{{ Passwort }}
checkbox|stayfield|{{ eingeloggt bleiben }}
ycom_auth_returnto|returnTo|

```

bekomme ich nach dem absenden folgende Fehlermeldung:

![image](https://github.com/FriendsOfREDAXO/yform_usability/assets/330516/52efb4f1-80ba-48bb-8d8b-b302e527baef)

![image](https://github.com/FriendsOfREDAXO/yform_usability/assets/330516/f4003b96-e94e-4944-88e4-8db6db60bfd1)

Wenn ich in der Datei yform_usability/lib/yform/lang_tabs.php um die Zeile 13 anfrage ob es sich gerade um das backend handelt funktioniert alles einwandfrei..

```
    function enterObject()
    {
        if(rex::isBackend()) {
            $this->params['form_output'][$this->getId()] = $this->parse('value.lang_tabs.tpl.php');
        }

    }
    
```

**Comment by alxndr-w** [comment]
@michael-kreatif was meinst du?

**Comment by michael-kreatif** [comment]
@olien + @alxndr-w Bug gefixt und getestet.
Hab die Lösung von Oliver übernommen, da beide Felder (lang_tabs + data_dump) eigentlich nur fürs Backend gedacht sind und die Templates bei Yform Usability auch nur im Backend aktuelle eingebunden werden(siehe boot.php)
