### ISSUE TITLE
List View Status Toggle löst kein YFORM_DATA_UPDATED Event aus

### ISSUE THREAD

**Issue by michael-kreatif** [FriendsOfREDAXO/yform_usability#150]
Wenn Datensätze über YForm (oder Yorm) gespeichert werden, wird ein `YFORM_DATA_UPDATED` (oder ADDED) Event getriggert.
Andere Extensions wie das URL Addon verlassen sich darauf und generieren dadurch die URLS für die betroffenen Datensätze.

YForm Usability speichert den Datensatz (status-Wert geändert) nicht über YOrm, sondern nur über rex_sql und besitzt dafür einen eigenen EP `YFORM_DATA_STATUS_CHANGED`.
Außerdem gibt es noch einen zweiten zusammenhängenden Bug. 
Der EP `YFORM_DATA_STATUS_CHANGED` wird zwar in der List-View getriggert. Dadurch, dass aber der Aufruf bereits in Usability direkt behandelt wird, ohne dass die anderen Addons (packages) included werden, kann man in den anderen Addons nicht auf das Event horchen.

**Comment by skerbis** [comment]
Gerade auch gemerkt.
