### ISSUE TITLE
SQL-Fehler bei Inline Suche nach Update YForm

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/yform_usability#156]
**Description / Beschreibung**
nach Update von YForm von 4.0.4 auf 4.1.1 funktioniert die Inline Suche bei mir nicht mehr. Die Suchergebnisse werden zwar angezeigt, bei Klick auf einen Ergebnisdatensatz stimmt die SQL-Abfrage aber nicht mehr. 
Beispiel: "SELECT `t0`.* FROM `rex_yform_table` AS `t0` WHERE `t0`.`id` = :where1 AND ( AND (`id` = ... 

siehe das doppelte AND 

**Affected versions / Verwendete Versionen**
2.0.9, 2.1.1

REDAXO: 5.15.1
PHP: 8.1.7
Database: MariaDB 10.6.12
Browser: 
AddOns:

**Comment by michael-kreatif** [comment]
@fietstouring danke für den Report. Hab nun den Bug gefixt und ein neues Release erstellt (2.1.1). 
Kannst du bitte prüfen, ob die neue Version bei dir passt?

**Comment by fietstouring** [comment]
Danke für die Arbeit, Fehler ist gefixt!

Am 4. September 2023 16:09:12 MESZ schrieb michael-kreatif ***@***.***>:
>@fietstouring danke für den Report. Hab nun den Bug gefixt und ein neues Release erstellt (2.1.1). 
>Kannst du bitte prüfen, ob die neue Version bei dir passt?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/FriendsOfREDAXO/yform_usability/issues/156#issuecomment-1705337180
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
