### ISSUE TITLE
drag & drop Sortierung funktioniert nicht

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/yform_usability#158]
**Description / Beschreibung**

drag & drop Sortierung über Hamburger-Icon funktioniert in Version 2.1.1 nicht mehr.
Problem scheint folgende Zeile zu sein, da `rex::isBackend()` offenbar 0 zurückgibt:
https://github.com/FriendsOfREDAXO/yform_usability/blob/05def13687d35f22eb22e8d947725f397d3eabee/lib/Api.php#L23

Wenn ich `!rex::isBackend() || ` entferne, klappt es. Im Backend bin ich natürlich eingeloggt. 
Siehe: https://github.com/FriendsOfREDAXO/yform_usability/commit/a5385d556062f7b3e7074fddfacfabe2a31850cd#diff-b124c612bcd2fc908d9c404f89fdf18109f53892acc45d8865cc5fa27d583ec2

**Affected versions / Verwendete Versionen**
2.1.1 
2.1.1-beta

<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.9, MariaDB 10.6.13)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.2.9                          |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.6.13 |
| Character set | utf8            |

| Database 2    |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.6.13 |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/117.0 |
|      Protocol | HTTP/1.0      |
|         HTTPS | no            |

| Packages                          |             |
| --------------------------------: | :---------- |
|                           adminer | 1.9.3       |
|                   article_presets | 1.3.0       |
|                             avcal | 1.2.1       |
|                            backup | 2.9.0       |
|                       be_password | 2.0.1       |
|                          be_style | 3.2.0       |
|               be_style/customizer | 3.2.0       |
|                   be_style/redaxo | 3.2.0       |
|                          be_tools | 1.7.9       |
|                           bloecks | 3.1.1       |
|                  bloecks/cutncopy | 3.1.1       |
|                 bloecks/dragndrop | 3.1.1       |
|                    bloecks/status | 3.1.1       |
|                    bs5_iconpicker | 1.0.5       |
|                     clear_content | 1.1.1       |
|                   consent_manager | 4.1.4       |
|                           cropper | 2.0.2       |
|                         developer | 3.9.2       |
|                        focuspoint | 4.0.4       |
|                        hyphenator | 1.3.0       |
|                           install | 2.11.1      |
|                            massif | 1.0.0       |
|                     massif_minify | 1.3.3       |
|                   massif_settings | 1.0.0       |
|                            mblock | 3.4.13      |
|                     media_manager | 2.14.0      |
|          media_manager_responsive | 1.1.5       |
|                  media_negotiator | 4.0.0alpha1 |
|                         mediapool | 2.13.0      |
|                          metainfo | 2.10.0      |
|                             mform | 7.3.0       |
|                         phpmailer | 2.12.0      |
|                              plyr | 3.23.3      |
|                           project | dev         |
|                          speed_up | 1.3.1       |
|                             sprog | 1.5.1       |
|                        statistics | 3.0.1       |
|                         structure | 2.15.0      |
|                 structure/content | 2.15.0      |
|                 structure/history | 2.15.0      |
|                  structure_tweaks | 1.4.0       |
|                             theme | 1.4.0       |
|                        theme_lock | 1.0.0       |
|                          tinymce5 | 1.2.17      |
|                          ui_tools | 1.2.2       |
| ui_tools/bootstrap-datetimepicker | 4.17.47     |
|        ui_tools/jquery-minicolors | 2.4.0       |
|                ui_tools/selectize | 0.2.0       |
|                          uploader | 2.4.1       |
|                               url | 2.1.0       |
|                         useragent | 2.3.0       |
|                             users | 2.10.0      |
|                             yform | 4.1.1       |
|                       yform/email | 4.1.1       |
|                     yform/manager | 4.1.1       |
|                       yform/tools | 4.1.1       |
|                     yform_adminer | 1.2.0       |
|                     yform_geo_osm | 1.2.8       |
|                  yform_quick_edit | 1.0.1       |
|             yform_spam_protection | 2.0-beta4   |
|                   yform_usability | 2.1.1       |
|                       ynewsletter | 1.5.1       |
|                          yrewrite | 2.10.0      |

</details>

**Did it whoops? / Whoops erhalten?**

Nope

**Comment by michael-kreatif** [comment]
@ynamite danke für den Report. 
Hab den Bug gefixt und ein neues Release 2.1.2 erstellt.
Kannst du bitte die neue Version auschecken und prüfen, ob es nun bei dir passt? Bitte um kurzes Feedback.

**Comment by ynamite** [comment]
Perfekt, funktioniert. Vielen Dank für die schnelle Behebung!

**Comment by isospin** [comment]
in der datentabelle tritt funktioniert es, aber auf der 'felder editieren' seite werden änderungen der reihenfolge nicht übernommen.

**Comment by michael-kreatif** [comment]
@isospin stimmt, danke, hab ich übersehen, dass dort auch nochmal die Drag and Drop Funktionalität greift. Wurde gefixt.
Kannst du bitte das neue Release auschecken (2.1.3) und kurz prüfen? Danke

**Comment by isospin** [comment]
funktioniert! vielen dank!
