### ISSUE TITLE
Bug - status Feld DropDown Schnellauswahl - Änderung wird nicht übernomme - Script hängt

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/yform_usability#162]
yform_usability | 2.1.3
yform | 4.1.1
Redaxo 5.15.1

habe ein Feld "choice | status | Freigabe" mit Auswahlmöglochkeit "offline=0,online=1,nur Detailseite online=2"

In der Übersichtstabelle wird eine Änderung des status Feldes nicht übernommen - wählt man ein anderen Status per DropDown aus so kommt der blaue animierte Kreis und bleibt ohne die Änderung zu überenhem - das JavaScript(?) dürfte sich aufhängen ...  
Auch nach Neuladen der Seite im Browser ist immer noch der alte Status.

**Comment by michael-kreatif** [comment]
@steri-rex sollte nun in Version 2.1.4 funktionieren. Kannst du bitte kurz testen und Feedback geben? LG

**Comment by steri-rex** [comment]
@michael-kreatif  ja funktioniert - vielen dank!
