### ISSUE TITLE
Update to 2.1.4 fails due to checksum error 

### ISSUE THREAD

**Issue by bpedersen2** [FriendsOfREDAXO/yform_usability#164]
**Description / Beschreibung**

**Affected versions / Verwendete Versionen**
 2.1.4 

REDAXO:  5.15.1
PHP: 8.1.22

**Did it whoops? / Whoops erhalten?**

```AddOn yform_usability konnte aus folgendem Grund nicht aktualisiert werden:
Die Prüfsumme der heruntergeladenen Zip-Datei stimmt nicht mit der erwarteten überein. Bitte in wenigen Minuten noch einmal probieren!```

**Comment by alxndr-w** [comment]
`Bitte in wenigen Minuten noch einmal probieren!` - das ist eine Meldung vom REDAXO-Installer und nicht von diesem Addon.
