### ISSUE TITLE
OutputFilter wird nicht aufgerufen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#17]
Ich habe versucht, die Bezeichnung "online" durch "verfügbar" mittels OutputFilter zu ersetzen. Beim Wechsel des Status geht die Ersetzung verloren, stattdessen steht dann wieder "online" oder "offline" dran.

Ist dies ein yform_usability-Problem oder eins vom Core selbst?

**Comment by lexplatt** [comment]
Dies ist, weil der Statuswechsel mittels AJAX Aufruf manipuliert wird und der Endpoint dafür nie den Output-filter Extensionpoint called

**Comment by alexplusde** [comment]
Also ein Problem vom Core?
