### ISSUE TITLE
Bezeichnung online/offline austauschbar machen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#18]
Bei manchen Datensätzen passt online/offline nicht so recht. Ich würde diese Bezeichnungen gerne bearbeitbar machen. Würde man bspw. eine Checkbox, einen Radio-Button oder ein SQL-Feld als `status` anlegen, könnte das yform_usability-Addon nachsehen, welche Value-Parameter dem Feld für 0 und 1 übergeben wurden, bspw.:

`offline=0,online=1`
`belegt=0,verfügbar=1`
`###placeholder0###=0,###placeholder1###=1`

**Comment by lexplatt** [comment]
Habe das nun umgesetzt und auf den aktuellen Github Branch geladen. Willst dus mal testn?

**Comment by alexplusde** [comment]
gerne
