### ISSUE TITLE
Felder in Felddefintion sortierbar machen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#19]
Könnte man die Felddefinitionen ebenfalls sortierbar machen? Diese verfügen grundsätzlich über ein prio-Feld und wie oft ist es zumindest uns schon passiert, dass wir nachträglich Felder neu sortieren mussten und dabei jedes Mal in die Felddefinition klicken mussten.

**Comment by IngoWinter** [comment]
Imho verhält es sich hier wie in https://github.com/FriendsOfREDAXO/yform_usability/issues/20 - die Funktion nutze ich viel zu selten, als dass ich dafür was programmieren wollte. Kurz zur Orientierung was ich meine: https://xkcd.com/1205/

**Comment by alexplusde** [comment]
Wir haben den Fall recht häufig, da würde xkcd.com/1205/ für uns sprechen. Z.B., wenn nachträglich Felder in fieldsets gruppiert und umsortiert werden. (Ja, ein gutes Konzept würde nachträgliche Überraschungen verhindern, aber darauf habe ich keinen Einfluss)

**Comment by IngoWinter** [comment]
Ja nu, hau rein :)
Oder zeig deinem Chef die Tabelle und rechne ihm vor, wieviel Kohle er mit dem Feature machen kann damit er Budget dafür locker macht.

**Comment by alexplusde** [comment]
;)
