### ISSUE TITLE
Tabellen sortierbar machen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#20]
Die Liste der Tabellen im TableManager könnten ebenfalls sortierbar gemacht werden.

**Comment by IngoWinter** [comment]
Technisch möglich ja - sinnvoll und lohnenswert meiner Meinung nach nicht. Das Kosten/Nutzenverhältnis passt an dieser Stelle einfach nicht. Wenn keiner Einwände hat - sprich das machen möchte :) - mach ich hier zu.
