### ISSUE TITLE
Notices

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/yform_usability#21]
Notice: Undefined index: duplicate_tables in /src/addons/yform_usability/lib/Extensions.php on line 27
Notice: Undefined index: status_tables in /src/addons/yform_usability/lib/Extensions.php on line 28
Notice: Undefined index: sorting_tables in /src/addons/yform_usability/lib/Extensions.php on line 29

Neueste Version

**Comment by IngoWinter** [comment]
duplicate_tables, status_tables und sorting_tables gibts erst seit dem 5. April: https://github.com/FriendsOfREDAXO/yform_usability/commit/70e7102e57b80926a32789e4fe4ecd56e6d7fa80#diff-3b7de2cf163f18aa521c050bb543084f. Diese Config Einträge werden über die install.php gesetzt - jedoch nur, wenn noch überhaupt keine Config Einträge für yform_usability existieren: https://github.com/FriendsOfREDAXO/yform_usability/blob/master/install.php#L18-L25

Einmal das Addon komplett löschen und neu installieren behebt das Problem - mehr würde ich da auch nicht machen. Die Anzahl der Nutzer, die dieses Problem betrifft, dürfte gegen 0 gehen...
