### ISSUE TITLE
structure_usability und addon_usability: Kategorien und Addon-Tabellen 

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#24]
Gibt es eine Möglichkeit, die Sortier-Funktion auch für die Structure und Addon-Tabellen, die mit Redaxo-Bordmitteln erstellt wurden, freizuschalten?

Weitere Idee dazu wäre, per Drag & Drop-Kategorien und Artikel verschieben zu können.

**Comment by lexplatt** [comment]
ich werds mir mal anschauen ;)

**Comment by IngoWinter** [comment]
Wenn keiner was dagegen hat, mache ich das Issue hier zu. Imho ist das kein yform_usability Issue, sondern ein Core Featurewunsch/ Idee für ein komplett neues Addon. Sprich entweder als Featurewunsch beim Core anlegen oder ein Repo dafür aufmachen.

**Comment by alexplusde** [comment]
@IngoWinter oder es wird erweitert um ein Usability-Addon losgelöst von YForm. Bitte nicht 100 kleine Addons, die alle miteinander verwandt sind ;)

**Comment by IngoWinter** [comment]
@alexplusde aus yform_usability wird 100%ig kein Usability-Addon. Offensichtlich hat keiner der Beteiligten  die Zeit für so ein Monster. Thematisch ist yform_usability ziemlich weit ab von dem, was du möchtest. Besser passen würde zb https://github.com/FriendsOfREDAXO/bloecks - da bist du zumindest schon mal in der Struktur (und Drag & Drop hats da auch).
