### ISSUE TITLE
Notice / Status Änderung

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/yform_usability#26]
`Notice: Undefined offset: 2 in /Users/ok/Sites/abc/redaxo/src/addons/yform_usability/lib/Utils.php on line 24
 `

Auch lässt sich der Status von online auf offline nicht ändern. Andersrum geht es...

![status](https://user-images.githubusercontent.com/330516/29171036-592a72ae-7ddb-11e7-892a-34147e8f4cf8.png)

**Comment by IngoWinter** [comment]
@olien probier mal die aktuelle gh version (oder tausch einfach den dateiinhalt der Utils.php). Ich hab was geändert: https://github.com/FriendsOfREDAXO/yform_usability/commit/31b068efc3d1bdb95150ed448379f80a485bb290

**Comment by IngoWinter** [comment]
Ist nun im Installer

**Comment by olien** [comment]
Habs nochmal getestet. Funktioniert einwandfrei. Super. Danke!
