### ISSUE TITLE
Changelog nötig?

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/yform_usability#29]
Mir ist grad aufgefallen, dass es ein Changelog gibt https://github.com/FriendsOfREDAXO/yform_usability/blob/master/Changelog.md
Hängt da jemandes Herzblut dran? Letztendlich haben wir durch die Releases ein Changelog und ich hab keinen Nerv zusätzlich nochmal alles in irgendeine Datei zu tippern. Yay or Nay für löschen bitte :)

**Comment by lexplatt** [comment]
...war mein erster Changelog überhaupt :)
kann von mir aus weck; ich finde es nur wichtig dass man im Release versteht, welche Änderungen man eigentlich installiert/aktualisiert. Ich habe diese Infos dann immer aus dem Changelog kopiert.
Wie handhabst du das?

**Comment by IngoWinter** [comment]
Ich mach zuerst das Github Release fertig. Dessen Beschreibungstext sollte eigentlich 1:1 für Redaxo Installer Release passen. Die Beschreibungen sind bisher eher minimal https://github.com/FriendsOfREDAXO/yform_usability/releases weils alles nur Bugfixes/ Kleinkram war, der beim Update keinen Stress machen kann.
