### ISSUE TITLE
Duplizieren: Bug, wenn man sich in einer gefilterten Ansicht befindet

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_usability#31]
Wenn man sich in einer be_manager_relation-Tabelle (popup 1:n) befindet und einen Datensatz dupliziert, geht die Filterung verloren und man sicht plötzlich alle Datensätze.

**Comment by IngoWinter** [comment]
Nach Klick auf den Duplizieren Link wird [dieses Skript aufgerufen](https://github.com/FriendsOfREDAXO/yform_usability/blob/master/pages/yform.manager.yform-usability.php#L40). Das dupliziert den Datensatz und macht dann einen Redirect auf die Liste - komplett ohne Parameter. Wenn man die gleiche Ansicht wie vor dem Duplizieren haben möchte, muss man sämtliche Parameter wieder in den Redirect packen - PR welcome sag ich  :)

**Comment by alexplusde** [comment]
Dann fehlen da wohl die Parameter. Falls es dir möglich wäre, was zu machen - du bist da näher dran.

**Comment by IngoWinter** [comment]
Ich bin weiter weg :)
Ich hab noch nie ne 

> be_manager_relation-Tabelle (popup 1:n)

 benutzt und auch noch nie irgendwas gefiltert. Ich müsste das jetzt erstmal aus nix was Zusammenstricken, damit ich das Verhalten überhaupt nachvollziehen kann. In der Zeit solltest du die entsprechenden Parameter schon durchgezogen haben.

**Comment by IngoWinter** [comment]
Dicke Finger und Touchpad :)
