### ISSUE TITLE
pjax-Fehler bei unterschieden zwischen www./nicht-www.-Domains

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_usability#32]
beim Ändern der Reihenfolge, duplizieren, etc., hört die Ladeanimation nicht mehr auf, wenn Backend-URL und Frontend-URL nicht korrespondieren, oder www. nicht enigegeben wurde.

**Comment by IngoWinter** [comment]
Welche Version? 1.3.0 oder älter? Und tritt der Fehler noch auf, wenn du ein Downgrade auf 1.2.8 machst?

**Comment by alexplusde** [comment]
aktuelle Installer-Version 1.3.0 - downgrade kann ich mal versuchen.

**Comment by IngoWinter** [comment]
Hängt vielleicht hiermit zusammen: https://github.com/FriendsOfREDAXO/yform_usability/issues/44

**Comment by alexplusde** [comment]
Ja.
