### ISSUE TITLE
pjax-Fehler, wenn Status einen ungültigen Wert enthält, bspw. NULL / ""

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#33]
Die Ladeanimation wird nicht mehr gestoppt, wenn man einen Status bspw. von "" auf "0" oder "1" setzen möchte. Falls bisher ein ungültiger Wert oder gar kein Wert dem Datensatz zugeordnet war, hängt sich dadurch Redaxo auf.

**Comment by IngoWinter** [comment]
Welche Version? 1.3.0 oder älter? Und tritt der Fehler noch auf, wenn du ein Downgrade auf 1.2.8 machst?

**Comment by alexplusde** [comment]
aktuelle Installer-Version 1.3.0 - downgrade kann ich mal versuchen.

**Comment by lexplatt** [comment]
habe soeben eine neue Version (1.3.1) veröffentlicht. @alexplusde könntest du bitte überprüfen ob es bei dir diesen Fehler löst?

**Comment by alexplusde** [comment]
Hab mir eine Memo fürs Wochenende gemacht.

**Comment by alexplusde** [comment]
gelöst.
