### ISSUE TITLE
schnelles Online/Offline funktioniert nicht

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/yform_usability#4]
HI,
ich habe in yForm folgendes Feld angelegt:
**Typname:** emptyname
**Bezeichnung:** status
Die on/offline Buttons erscheinen in der yForm Tabelle.
Auch der Klick funktioniert. Nur leider ändert sich nichts in der DB und
nach dem erneuten Aufruf der yForm tabelle sind alle wieder offline.

Danke. grz. Chris

**Comment by alexplusde** [comment]
Dieses Verhalten kann ich nachstellen bei bestehenden Datensätzen.

Sobald man einen Datensatz bearbeitet und dann an diesem Datensatz online/offline vornimmt, funktioniert das Umschalten.

Evtl. hier initial alle Datensätze mal mit `0` befüllen.

**Comment by lexplatt** [comment]
Habe nun die Update-Query geändert und somit sollte das Problem gelöst sein
