### ISSUE TITLE
Sortierung per Drag&Drop und on -offline funktioniert nicht - https?

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/yform_usability#44]
ich weiss nicht ob es vielleicht mit https zusammenhängt - da es bei der kopie der webseite ohne https funktioniert.
jedenfalls kann ich in der tabelle weder per drag und drop sortieren noch "online" stellen - es kommt in der Konsole die Fehlermeldung 

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://www.domain.de/index.php?rex-api-call=yform_usability_api&method=changeStatus. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://www.domain.de/index.php?rex-api-call=yform_usability_api&method=updateSort. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

**Comment by steri-rex** [comment]
wenn man in redaxo über **https**://www.domain.de/redaxo eingeloggt ist funktionierts - ich war über **http**://www.domain.de/redaxo eingeloggt da funktionierts dann nicht.

**Comment by svenkaemper** [comment]
Hatte das gleiche Problem mit dem Sked Kalender, da wurden die Termine in der Kalenderansicht nicht geladen und in der Konsole stand die Meldung mit "Access-Control-Allow-Origin" … 

Ich vermute, es hängt vielleicht mir der Domain aus yRewrite zusammen und man sollte das Redaxo-Backend über die Domain aufrufen, die dort angegeben ist. In meinem Fall war dort http://domain.de hinterlegt – bei Aufruf des Redaxo-Backends über http://**www**.domain.de kommt es zur Fehlermeldung.

**Comment by steri-rex** [comment]
ja das dürfte wirklich mit yRewrite zusammen hängen - ist bei mir auch so: dadurch dass ich im yRewrite https://www eingetragen habe, muss man sich auch über https://www in redaxo einloggen damit die Fehlermeldung nicht kommt

**Comment by IngoWinter** [comment]
Hier zb wird der Aufruf für den Status (online/offline) gemacht: 
https://github.com/FriendsOfREDAXO/yform_usability/blob/master/assets/script.js#L12

Der Aufruf geht an `rex.frontend_url`, die nicht mit der aktuellen url übereinstimmen muss. Hier wäre es dann vermutlich schlauer, sich die aktuelle url zu holen: https://stackoverflow.com/questions/6941533/get-protocol-domain-and-port-from-url

**Comment by alexplusde** [comment]
Problem besteht weiterhin.

**Comment by alxndr-w** [comment]
Das ist längst mit einem Commit aus 2019 behoben.
