### ISSUE TITLE
Assets werden beim Update / Reinstallieren nicht aktualisiert

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#46]
https://github.com/FriendsOfREDAXO/yform_usability/blob/4494e702851412bbb69b6d1f41ee87f337bfa9f4/assets/scss/styles.scss#L7

Aus irgendwelchen Gründen landet diese Zeile später nicht im CSS.

**Comment by IngoWinter** [comment]
schon mal reinstalliert? bei mir stehts drin...

**Comment by IngoWinter** [comment]
schon mal die styles.css gelöscht?

**Comment by alexplusde** [comment]
deinstallieren und installieren hat geholfen.

Das ist unbefriedigend, hier müsste yform_usability die assets beim Updaten / Reinstallieren überschreiben.
