### ISSUE TITLE
Statusfeld von rex_ycom_user ohne Übersetzung

### ISSUE THREAD

**Issue by tema-web** [FriendsOfREDAXO/yform_usability#47]
Wenn bei yform_usability "Online/Offline Status anzeigen" für alle Tabellen angewählt ist werden die Status-Einträge der Tabelle rex_ycom_user nicht übersetzt.
![bildschirmfoto 2018-05-15 um 17 43 23](https://user-images.githubusercontent.com/1210088/40068072-02a913c8-5868-11e8-80ab-11e8c818f719.png)

**Comment by alexplusde** [comment]
+1
