### ISSUE TITLE
Inkompatibilität mit YForm 3.0

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#51]
https://github.com/yakamara/redaxo_yform/issues/519

**Comment by lexplatt** [comment]
ich habe das gefixt, leider noch nicht veröffentlicht. kannst du das kurz besätigen ob es bei dir mit der Github-Version läuft?

**Comment by alexplusde** [comment]
Das kann ich frühestens nächste Woche leider...
