### ISSUE TITLE
Manager: Spalten einer Tabelle verlieren beim editieren der Spalte die Position/Prio

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/yform_usability#58]
Die Prio von yform Manager Tabellen Spalten werden durch yform_usability durcheinander gebracht und gehen beim Editieren ggf. verloren bzw. stimmen nicht mehr.

yform/manager 3.0
yform_usability 1.4

Hier ein konkretes Beispiel (wo der Fehler aktuell auftritt).

<img width="907" alt="grafik" src="https://user-images.githubusercontent.com/1733051/55360063-9ec42c80-54d3-11e9-8157-e19566abe282.png">

Wenn ich hier beispielsweise beim Feld `url_beruf` auf editieren klicke, erscheint folgendes:

<img width="910" alt="grafik" src="https://user-images.githubusercontent.com/1733051/55360329-52c5b780-54d4-11e9-9e83-b03f0fbe85e4.png">

Wie man sieht, wird das Select-Feld `Priorität` ohne mein Zutun auf "Am Anfang" gesetzt. Wenn man nun speichert, ohne es zu bemerken, stimmt die Feld-Reihenfolge nicht mehr. Der Fehler bleibt solange bestehen, bis man im Select-Feld irgendeine andere Reihenfolge wählt als "Am Anfang". Danach werden die Prios korrekt neu gesetzt:

<img width="903" alt="grafik" src="https://user-images.githubusercontent.com/1733051/55361596-fc5a7800-54d7-11e9-87a2-769dd2bcb364.png">

https://github.com/yakamara/redaxo_yform/issues/661

**Comment by isospin** [comment]
ich kann das problem bestätigen

REDAXO 5.7.1
yform_usability 1.4
yform/manager 3.1.1
