### ISSUE TITLE
TableManager Tableset exportieren nicht möglich

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/yform_usability#60]
Fehlermeldung "[Warnmeldung für Feld `table_names` fehlt]"
![Bildschirmfoto 2019-05-23 um 11 23 47](https://user-images.githubusercontent.com/17403820/58242259-c35bb880-7d4e-11e9-970f-ae9f7f7a86bb.png)

**Comment by alxndr-w** [comment]
Das ist kein Feature von YForm Usability.
