### ISSUE TITLE
YCom User-Übersicht: Undefined istatus

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#61]
`Notice | Undefined variable: istatus | redaxo\src\addons\yform_usability\lib\Utils.php`

für jeden Datensatz in der Übersicht.

**Comment by Hirbod** [comment]
Habs gefixt und mal ein release 1.4.1 geschnürt.

**Comment by Hirbod** [comment]
Hab das release gelöscht, da es aktuell noch ein ziemlicher verbuggter beta stand ist

**Comment by alexplusde** [comment]
Ehm ok. Einfach Bescheid geben, wenn ich was tun kann...

**Comment by Hirbod** [comment]
Das AddOn verändert die komplette yForm Suche (nicht einstellbar), deswegen hab ich das Release entfernt, da es leider nicht nur dieses Problem fixed sondern halt unfertige Features enthält. Eigentlich müsste man nen zweiten Branch machen

**Comment by lexplatt** [comment]
ich werds so abändern dass die suche optional wird

**Comment by Hirbod** [comment]
Ich find deinen Suchansatz ehrlich gesagt sehr gut, aber es bedarf noch einiges an Ausarbeitung. Unter anderem optisch und technisch. Suche mit den Default Platzhaltern ist nicht mehr möglich, das X fliegt unter der Form rum, der Focus geht nach der Ajax Suche verloren, es gibt undefined offset errors.

Aber ansonsten finde ich es deutlich angenehmer als dieser riesige linke Spaltenflatschen, den yForm mitbringt.

**Comment by Hirbod** [comment]
@skerbis ich kann diesen Fehler nicht reproduzieren. Weder auf PHP 7.2 noch auf 7.3. Error Reportings sind ebenfalls aktiv. Im Redaxo Log stehen auch nur Warnings und Notices von yRewrite.

**Comment by alexplusde** [comment]
ist mir nicht mehr begegnet.
