### ISSUE TITLE
Notice in Verbindung mit yCom AddOn

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/yform_usability#72]
Wird für jeden Datensatz ausgegeben:

`Undefined variable: istatus | redaxo/src/addons/yform_usability/lib/Utils.php`

REDAXO & AddOns aktuell.

Gruß
Oliver

**Comment by olien** [comment]
Weil es dort schon ein status Feld gibt...

**Comment by alxndr-w** [comment]
Das wurde schon in der GitHub-Version gefixt. @lexplatt spricht etwas gegen einen Release?
