### ISSUE TITLE
Übersetzungen werden nicht gezogen

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/yform_usability#73]
Ändert man in den Lang Dateien von yform_usability.help_prio  auf usability.help_prio werden die Übersetzungen angezeigt.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/yform_usability/pull/64

**Comment by alxndr-w** [comment]
@rkemmere @skerbis ist das in der aktuellen GitHub-Version noch der Fall?

**Comment by rkemmere** [comment]
In der aktuellen Version aus dem Git ist es in Ordnung!
