### ISSUE TITLE
offline/online: cursor: pointer;

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#8]

**Comment by Hirbod** [comment]
Hätt ich gleich auch noch als PR senden sollen. Hatte schon cursor: move fürs drag/drop eingebaut

**Comment by Hirbod** [comment]
Oh, ist schon drin! Dann closed?

**Comment by lexplatt** [comment]
Stimmt, danke für den PR

**Comment by alexplusde** [comment]
bei mehreren Spalten findet ein Umbruch statt von Icon und Beschriftung (`online/offline`). Vlt. nochmal vergleichen mit dem Syntax / CSS von `structure`
