### ISSUE TITLE
yform4: Problem mit duplizieren: Adresse wird nicht gefunden

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_usability#84]
https://github.com/FriendsOfREDAXO/yform_usability/pull/83
Behebt das Problem nicht. 

https://domain.de/index.php?_csrf_token=K-VNbJNge9coz2mmOqnK8vYX5jXB1h9IMK531-WsuAU&rex-api-call=yform_usability_api&method=changeStatus

wird nicht gefunden, stattdessen wird der 404 geladen.

<details>
<summary>System report (REDAXO 5.13.1, PHP 7.4.27, MariaDB 10.2.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.27     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.39 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.1 |
|      Protocol | HTTP/1.0    |
|         HTTPS | yes         |

| Packages                    |             |
| --------------------------: | :---------- |
|                     adminer | 1.9.2       |
|               animatedlogin | 1.0.0       |
|                      backup | 2.8.0       |
|                    be_style | 3.0.0       |
|         be_style/customizer | 3.0.0       |
|             be_style/redaxo | 3.0.0       |
|                    be_tools | 1.7.3       |
|                     bloecks | 3.1.1       |
|            bloecks/cutncopy | 3.1.1       |
|           bloecks/dragndrop | 3.1.1       |
|                        cke5 | 5.0.2       |
|             consent_manager | 3.0.3       |
|                     cronjob | 2.8.1       |
|                     cropper | 1.2.0       |
|               fa-iconpicker | 0.3 beta    |
|                      ffmpeg | 1.0.0       |
|                  focuspoint | 4.0.0       |
|             global_settings | 2.7.1       |
|                  hyphenator | 1.2.0       |
|                    icecoder | 3.0.0       |
|                     install | 2.9.3       |
|                klxm_website | 2.0.0       |
|                      locked | 1.0.1       |
|                 maintenance | 2.6.4       |
|                      matomo | 1.2.1       |
|                      mblock | 3.4.4       |
|               media_manager | 2.12.1      |
|                media_srcset | 2.0.5-dev   |
|                   mediapool | 2.11.1      |
|                    metainfo | 2.8.3       |
|                       mform | 6.1.2       |
|                  mform/docs | 1.1         |
|                     minibar | 2.3.0       |
|            navigation_array | 1.2.0       |
|                    osmproxy | 1.6.0       |
|                      pdfout | 4.1.2       |
|                   phpmailer | 2.11.1      |
|                        plyr | 3.15.3      |
|                     project | dev         |
|            quick_navigation | 5.2.1       |
|                   search_it | 6.9.0       |
|     search_it/documentation | 6.9.0       |
|             search_it/stats | 6.9.0       |
|                  seocheckup | 1.6.3       |
|                       sprog | 1.3.0       |
|                   structure | 2.13.1      |
|           structure/content | 2.13.1      |
|           structure/history | 2.13.0      |
|                    uploader | 2.3.0       |
|                         url | 2.0.0-dev   |
|                       users | 2.8.2       |
|                      watson | 2.2.0       |
|               xoutputfilter | 3.0.0-beta1 |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
|                       yform | 4.0.0       |
|                 yform/email | 4.0.0       |
|               yform/manager | 4.0.0       |
|                  yform/rest | 4.0.0       |
|                 yform/tools | 4.0.0       |
|               yform_geo_osm | 1.2.5       |
|             yform_usability | 1.11.0      |
|                    yrewrite | 2.8.3       |
|    yrewrite_domain_settings | 2.0.2       |
|             yrewrite_scheme | 3.6.1       |
|                 zip_install | 1.1         |

</details>

**Comment by alxndr-w** [comment]
@skerbis wie kann es sein, dass du YForm Usability 1.11.0 verwendest, wenn die aktuelle Version 1.10.6 ist?

https://github.com/FriendsOfREDAXO/yform_usability/blob/1f1196677cd336d26c23347f114cb12db32cb05c/package.yml#L2

**Comment by alxndr-w** [comment]
gelöst mit #96
