### ISSUE TITLE
Installer-Release / Installer-Action im Repo

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_usability#86]
Die aktuelle Version im Installer ist `1.4` - hier im Repo gibt es bereits die `1.10.3` - die letzte veröffentlichte Version als GitHub-Release ist 1.3.4`

**Comment by alxndr-w** [comment]
Ich kann's auch machen, dann hätte ich gerne ein Okay vorher.

**Comment by alxndr-w** [comment]
Mit @skerbis telefoniert. Er würde die Installer-Action hier im Repo nachrüsten.

**Comment by skerbis** [comment]
Jupp mache ich  - gleich
