### ISSUE TITLE
Unterstützung für yform 4?

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/yform_usability#87]
Hallo, wird es die yform_usability auch für yform 4 geben? Wenn ja, wann ungefähr? Setze gerade zwei Projekte auf und
würde da gleich mit yform 4 einsteigen, die Funktionen der usability sind aber absolut notwendig...

Gibts nen Topf, in den ich was reinwerfen kann?

**Comment by polarpixel** [comment]
Ich habe auch Bedarf. Ggf. könnte ich auch ein wenig beisteuern. Die Funktion zum Duplizieren ist aktuell bei mir wichtig.

**Comment by alxndr-w** [comment]
Ich habe nichts gefunden, was bisher nicht funktioniert mit YForm 4. (D&D, Status-Schalter).

Ungeachtet dessen hat das Addon ein paar konzeptionelle Fehler wie das Umgehen der offiziellen EPs und fehlende optische Anpassungen an YF4 sowie der seit Ewigkeiten fehlenden Übersetzungsstrings. 

Langer Rede kurzer Sinn:
Ich würde auch was beisteuern.

**Comment by alxndr-w** [comment]
Siehe #75
