### ISSUE TITLE
Status: Validierung berücksichtigen, EP-Triggern, statt Status per DB-Aufruf zu ändern [für URL-Addon, EPs]

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/yform_usability#88]
Bei meiner Installation (Redaxo 5.12, yform 3.4, yform_usability 1.4) werden beim Status Toggle die Änderungen nicht mit dem URL-Addon synchronisiert. Im File Api.php Zeile 52 wird der addonCache von URL gelöscht aber nicht neu generiert.

**Comment by alxndr-w** [comment]
Wie es aussieht müsste dieser EP angepasst werden.

https://github.com/FriendsOfREDAXO/yform_usability/blob/a9db797576359bedad4e39b5ff0c3c1c03f21c2e/lib/Extensions.php#L23

**Comment by tbaddade** [comment]
Die Änderung des Status ist eine Änderung des Datensatzes und müsste es den EP `YFORM_DATA_UPDATED` von YForm triggern. Url würde daraufhin die Urls neu erstellen.

**Comment by alxndr-w** [comment]
Ich sehe, dass hier auch Anpassungen für das URL-Addon aufgenommen wurden (verm. URL1)

https://github.com/FriendsOfREDAXO/yform_usability/blob/a9db797576359bedad4e39b5ff0c3c1c03f21c2e/lib/Api.php#L43-L52

M.E. könnte man hier mit YOrm speichern, dann wird YFORM_DATA_UPDATED ja unweigerlich getriggert und es ist somit kompatibel zu YForm und URL2 gleichermaßen.

**Comment by tbaddade** [comment]
Die Zeile mit pathlist.php kann für Url 2 definitiv weg. Diese Datei existiert nicht mehr.

**Comment by alxndr-w** [comment]
Der PR konnte nicht fertiggestellt werden. Das Problem ist zu komplex für mich und andere scheint es nicht zu stören.

**Comment by alxndr-w** [comment]
Wenn sich jemand dafür findet und das bezahlt für 2-3 Zeitstunden bezahlt haben möchte, möge sich bitte bei mir melden.

**Comment by alxndr-w** [comment]
@fietstouring melde dich nochmal bei mir direkt, falls du eine Lösung brauchst. Ich habe das Status-Toggle jetzt unabhängig von yform_usability gelöst.

**Comment by fietstouring** [comment]
> @fietstouring melde dich nochmal bei mir direkt, falls du eine Lösung brauchst. Ich habe das Status-Toggle jetzt unabhängig von yform_usability gelöst.

Hi, sorry ich sehe deine Antwort erst jetzt. Ja gerne, wie und wo hast Du das gelöst?

**Comment by alxndr-w** [comment]
@fietstouring du darfst gerne das Value `choice_status` ausprobieren - Ergänzungen sind gerne willkommen (bspw. klassischer Status-Schalter offline/online als Links oder per Bootstrap-Dropdown).

https://github.com/alexplusde/yform_field/releases/tag/2.3.0

Wenn alles passt, dann kann das Issue hier geschlossen werden.
