### ISSUE TITLE
Beschränkte Prio-Felder sortieren können.

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_usability#9]
Siehe https://github.com/yakamara/redaxo_yform/issues/99

**Comment by alexplusde** [comment]
Das ist wirklich ein Bug, der die Usability-Erweiterung unbrauchbar macht, wenn man gefilterte Tabellen hat. Es sortiert einen Quark.

**Comment by alexplusde** [comment]
Bei gefilterten Tabellen wird im Moment zumindest wieder die gleiche Sortierung erzeugt, wie ohne yform_usability.

**Comment by alexplusde** [comment]
Wenn ich auf eine gefilterte Tabelle schaue und dann per drag + drop sortiere, werden die Reihenfolge-Zahlen über die Beschränkung hinweg neu vergeben. Richtig wäre, dass sie nur die beschränkten Datensätze sortieren.

**Comment by IngoWinter** [comment]
Hast du da einen Screenshot oder was anderes erhellendes zu? Ich bin mir nicht sicher, was gemeint ist.

**Comment by alexplusde** [comment]
prio-Feld einstellen auf "beschränken", bspw. eine Gruppe. Dabei werden prio-Werte in Abhängigkeit zur Beschränkung vergeben. Beispiel:

| id | name       | group  | prio |
|----|------------|--------|------|
| 1  | Radieschen | Gemüse | 1    |
| 2  | Gurke      | Gemüse | 2    |
| 3  | Karotte    | Gemüse | 3    |
| 4  | Apfel      | Obst   | 1    |
| 5  | Birne      | Obst   | 2    |

In einer be_manager_relation-popup-1:n Tabelle ist es mir möglich, nur einen Teil der Datensätze anzuzeigen, bspw. nur Gemüse:

| id | name       | group  | prio |
|----|------------|--------|------|
| 1  | Radieschen | Gemüse | 1    |
| 2  | Gurke      | Gemüse | 2    |
| 3  | Karotte    | Gemüse | 3    |

Sobald ich dann per Drag and Drop die Reihenfolge neu festlege (bspw. Karotte auf 1 schiebe), sieht die gesamte Tabelle aber so aus:

| id | name       | group  | prio |
|----|------------|--------|------|
| 3  | Karotte    | Gemüse | 1    |
| 1  | Radieschen | Gemüse | 2    |
| 2  | Gurke      | Gemüse | 3    |
| 4  | Apfel      | Obst   | 4    |
| 5  | Birne      | Obst   | 5    |

Vielleicht sollte man Drag & Drop bei beschränkten Prio-Feldern deaktivieren, schöner wäre es zumindest, wenn man wie im obrigen Beispiel aber nur innerhalb der Beschränkung sortieren kann.

**Comment by IngoWinter** [comment]
Ist letztendlich das gleiche Problem, wie bei der Duplizieren Geschichte - du müsstest der [zuständigen Funktion](https://github.com/FriendsOfREDAXO/yform_usability/blob/master/lib/Api.php#L61) mitteilen, dass sie nur nur für einen Teil der Tabelle neue IDs vergeben soll. Es gibt dort sogar schon eine passend scheinende Variable `$filter` vorhanden....
